### ISSUE TITLE
dayOfWeek 有bug

### ISSUE THREAD

**Issue by dunkboy** [a852203465/CronUtils#1]
每周星期几 几点执行 不好使 有bug

**Comment by a852203465** [comment]
好的， 我去验证下， 并修复




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a852203465/CronUtils"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 下午3:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[a852203465/CronUtils] dayOfWeek 有bug (Issue #1)





 
每周星期几 几点执行 不好使 有bug
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by a852203465** [comment]
你好，&nbsp; &nbsp;请提供下你的调用实例




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a852203465/CronUtils"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 下午3:43
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[a852203465/CronUtils] dayOfWeek 有bug (Issue #1)





 
每周星期几 几点执行 不好使 有bug
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dunkboy** [comment]
public CronBuilder dayOfWeek(Integer... dayOfWeeks) {
        setTime(1, dayOfWeeks);
        StringJoiner stringJoiner = new StringJoiner(COMMA);
        for (Integer dayOfWeek : dayOfWeeks) {
            if (dayOfWeek > 7)  dayOfWeek = 7;
            if (dayOfWeek < 1)  dayOfWeek = 1;
            stringJoiner.add(dayOfWeek + EMPTY);
        }

        if (isBlank(this.seconds)) seconds(0);
        if (isBlank(this.minutes)) minutes(0);
        if (isBlank(this.hours)) hours(0);
        if (isBlank(this.month)) month(1);
        this.dayofWeek = stringJoiner.toString();
        return this;
    }
永远是1月1号

**Comment by a852203465** [comment]
前提：生成cron表达式时， 由于使用者的不合理组装，为避免表达式无法执行，对子表达式做了一个默认值设置


规则：Cron 表达式的注意项之一：（?：只能用在DayofMonth和DayofWeek两个域。
它也匹配域的任意值，但实际不会。
因为DayofMonth和DayofWeek会相互影响。
例如想在每月的20日触发调度，不管20日到底是星期几，则只能使用如下写法： 13 13 15 20 * ?,&nbsp;
其中最后一位只能用？，而不能使用*，如果使用*表示不管星期几都会触发，实际上并不是这样。）


因此：对此dayOfMonth, dayofWeek有一定的规则匹配(会修改最终组装参数，使表达式能正常执行)， 现已修复， 你可再次尝试生成使用












------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "a852203465/CronUtils"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月22日(星期三) 下午4:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [a852203465/CronUtils] dayOfWeek 有bug (Issue #1)





 public CronBuilder dayOfWeek(Integer... dayOfWeeks) {     setTime(1, dayOfWeeks);     StringJoiner stringJoiner = new StringJoiner(COMMA);     for (Integer dayOfWeek : dayOfWeeks) {         if (dayOfWeek &gt; 7)  dayOfWeek = 7;         if (dayOfWeek < 1)  dayOfWeek = 1;         stringJoiner.add(dayOfWeek + EMPTY);     }     if (isBlank(this.seconds)) seconds(0);     if (isBlank(this.minutes)) minutes(0);     if (isBlank(this.hours)) hours(0);     if (isBlank(this.month)) month(1);     this.dayofWeek = stringJoiner.toString();     return this; }  
永远是1月1号
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dunkboy** [comment]
感谢！
